apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversao
spec:
  selector:
    matchLabels:
      app: conversao
  template:
    metadata:
      labels:
        app: conversao
    spec:
      containers:
        - name: conversao
          image: joaolm/conversao-temperatura-1:v1
          imagePullPolicy: Always
          ports:
          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: conversao
spec:
  selector:
    app: conversao
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30000
  type: NodePort